### ISSUE TITLE
FIRMWARE

### ISSUE THREAD

**Issue by igorgiavitto** [bgolab/JustBasic#8]
I try to load a firmware and all goes smooth, test some program and all ok. The firmware it's not persistent, after reset the card i found again the old circuit python firmare, thats it's right? or some bug ? or some wrong procedure? or also interpreter it's load in ram when load the firmware?

Thank you in advance

**Comment by bgolab** [comment]
Yes, this is expected. 

I added a note in the build folder to indicate that it was compiled for SRAM ONLY.
_NOTE: All current builds are compiled with 'no_flash' option so no flashing required to try the BASIC, just drag & drop the uf2 image into the PICO emulated disk._

I released such SRAM only builds for people just to try the interpreter without having to flash the PICO.

Of course I can release normal builds if you would like to play it. I have not released any build for a couple of weeks (holidays) but I'll be back soon and add new features, etc

**Comment by bgolab** [comment]
Have you tested the v1.0 or my latest v1.1 builds?

v1.1. is really new build (major changes to the architecture) - it passed all sanity tests (automated). It is still being modified - need to decide about new expr parser version. But it is pretty fast (or at least faster than v1.0)

**Comment by bgolab** [comment]
You can try this:
https://github.com/bgolab/JustPicoBasic/blob/main/builds/JustBasic-1.1b100_flash.uf2

although I did NOT test it.

**Comment by igorgiavitto** [comment]
Thank you very much for your quick replay. I play not professional with electronic since I was 7 years old 45 years ago :),
I like your work, yes for sure I will test the flash beta, I planning to use your interpreter for my simple home gadgets. Not understand if I use external eeprom any chance to autorun a program.

**Comment by bgolab** [comment]
Let me know the feedback. I will try to fix bugs quickly.

I am playing with electronics since 1983. Although I have electronic engineering degree I am rather hobbyist.

**Comment by bgolab** [comment]
Whenever a build for flash is needed just let me know. Currently JustBasic-1.1b100_flash.uf2 is available
