### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by georgestheking** [bgolab/JustBasic#9]
Hi,
Thanks for this project.
It will be nice to have Timer or Wait.

Best regards

Georges

**Comment by bgolab** [comment]
Hi,
Thank you for interesting in this project.

Currently we have two timer like functions:
DELAY x - stops the program for x millisec
GETTICK() - gets the current tick number in millisec - this way  you can read the time twice and compare the difference - if the difference is bigger than the time you want to wait you can do something - this is NON blocking approach to time measurement

Please see the manual:
https://github.com/bgolab/JustPicoBasic/blob/main/manuals/JustPicoBasic_v1.1b101.pdf

Please let me know if you need something else

**Comment by bgolab** [comment]
Blocking type of delay:

for k=1 to 5 print k pause 1000 next k

**Comment by bgolab** [comment]
NON-blocking waiting example (can do something while waiting):
waitTime=500
start=gettick()
while gettick()<start+waitTime
print "do something now while waiting"
endwhile
print "done!"

**Comment by bgolab** [comment]
Generally speaking it is easier to use blocking 'pause'. But need sometimes to do something while waiting  - for this reason gettick() is nicer.
